#! /usr/bin/env bash
set -euo pipefail

# Locate the script file. Cross symlinks if necessary.
loc="$0"
while [ -L "$loc" ]; do
  ls=`ls -ld "$loc"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    loc="$link" # Absolute link
  else
    loc="`dirname "$loc"`/$link" # Relative link
  fi
done
base_dir=`dirname "$loc"`

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 <benchmark-class-name> [caliper-args...]"
  exit 1
fi

exec java -cp $base_dir/target/classes:"$(cat "$base_dir/target/runtime-classpath")" "$@"
